export const STUDENT_CONTENT_STATUS_REQUEST = "STUDENT_CONTENT_STATUS_REQUEST"
export const STUDENT_CONTENT_STATUS_SUCCESS = "STUDENT_CONTENT_STATUS_SUCCESS"
export const STUDENT_CONTENT_STATUS_FAIL = "STUDENT_CONTENT_STATUS_FAIL"
export const STUDENT_CONTENT_STATUS_RESET = "STUDENT_CONTENT_STATUS_RESET"