export const STUDENT_CONTENT_STATUS_REQUEST = "STUDENT_CONTENT_STATUS_REQUEST"
export const STUDENT_CONTENT_STATUS_SUCCESS = "STUDENT_CONTENT_STATUS_SUCCESS"
export const STUDENT_CONTENT_STATUS_FAIL = "STUDENT_CONTENT_STATUS_FAIL"
export const STUDENT_CONTENT_STATUS_RESET = "STUDENT_CONTENT_STATUS_RESET"

export const FAQ_REQUEST = "FAQ_REQUEST"
export const FAQ_SUCCESS = "FAQ_SUCCESS"
export const FAQ_FAIL = "FAQ_FAIL"
export const FAQ_RESET = "FAQ_RESET"