export const FAQ_REQUEST = "FAQ_REQUEST";
export const FAQ_SUCCESS = "FAQ_SUCCESS";
export const FAQ_FAIL = "FAQ_FAIL";
export const FAQ_RESET = "FAQ_RESET";

export const STUDENT_ASSESSMENTS_REQUEST = "STUDENT_ASSESSMENTS_REQUEST"
export const STUDENT_ASSESSMENTS_SUCCESS = "STUDENT_ASSESSMENTS_SUCCESS"
export const STUDENT_ASSESSMENTS_FAIL = "STUDENT_ASSESSMENTS_FAIL"

export const STUDENT_QUIZZ_REQUEST = "STUDENT_QUIZZ_REQUEST"
export const STUDENT_QUIZZ_SUCCESS = "STUDENT_QUIZZ_SUCCESS"
export const STUDENT_QUIZZ_FAIL = "STUDENT_QUIZZ_FAIL"
export const QUIZZ_RESET = "QUIZZ_RESET"

