export const TEACHER_COHORT_REQUEST = "TEACHER_COHORT_REQUEST"
export const TEACHER_COHORT_SUCCESS = "TEACHER_COHORT_SUCCESS"
export const TEACHER_COHORT_FAIL = "TEACHER_COHORT_FAIL"
export const TEACHER_RESET = "TEACHER_RESET"

export const TEACHER_COURSES_REQUEST = "TEACHER_COURSES_REQUEST"
export const TEACHER_COURSES_SUCCESS = "TEACHER_COURSES_SUCCESS"
export const TEACHER_COURSES_FAIL = "TEACHER_COURSES_FAIL"