export const TEACHER_COHORT_REQUEST = "TEACHER_COHORT_REQUEST"
export const TEACHER_COHORT_SUCCESS = "TEACHER_COHORT_SUCCESS"
export const TEACHER_COHORT_FAIL = "TEACHER_COHORT_FAIL"
export const TEACHER_COHORT_RESET = "TEACHER_COHORT_RESET"

export const TEACHER_COURSES_REQUEST = "TEACHER_COURSES_REQUEST"
export const TEACHER_COURSES_SUCCESS = "TEACHER_COURSES_SUCCESS"
export const TEACHER_COURSES_FAIL = "TEACHER_COURSES_FAIL"
export const TEACHER_COURSES_RESET = "TEACHER_COURSES_RESET"

export const TEACHER_SESSIONS_REQUEST = "TEACHER_SESSIONS_REQUEST"
export const TEACHER_SESSIONS_SUCCESS = "TEACHER_SESSIONS_SUCCESS"
export const TEACHER_SESSIONS_FAIL = "TEACHER_SESSIONS_FAIL"
export const TEACHER_SESSIONS_RESET = "TEACHER_SESSIONS_RESET"

export const TEACHER_SESSION_SECTIONS_REQUEST = "TEACHER_SESSION_SECTIONS_REQUEST"
export const TEACHER_SESSION_SECTIONS_SUCCESS = "TEACHER_SESSION_SECTIONS_SUCCESS"
export const TEACHER_SESSION_SECTIONS_FAIL = "TEACHER_SESSION_SECTIONS_FAIL"
export const TEACHER_SESSION_SECTIONS_RESET = "TEACHER_SESSION_SECTIONS_RESET"

export const TEACHER_TEMP_SET = "TEACHER_TEMP_SET"
export const TEACHER_TEMP_RESET = "TEACHER_TEMP_RESET"

export const TEACHER_SESSION_STATUS_REQUEST = "TEACHER_SESSION_STATUS_REQUEST"
export const TEACHER_SESSION_STATUS_SUCCESS = "TEACHER_SESSION_STATUS_SUCCESS"
export const TEACHER_SESSION_STATUS_FAIL = "TEACHER_SESSION_STATUS_FAIL"
export const TEACHER_SESSION_STATUS_RESET = "TEACHER_SESSION_STATUS_RESET"

export const TEACHER_SESSION_UNLOCK_REQUEST = "TEACHER_SESSION_UNLOCK_REQUEST"
export const TEACHER_SESSION_UNLOCK_SUCCESS = "TEACHER_SESSION_UNLOCK_SUCCESS"
export const TEACHER_SESSION_UNLOCK_FAIL = "TEACHER_SESSION_UNLOCK_FAIL"
export const TEACHER_SESSION_UNLOCK_RESET = "TEACHER_SESSION_UNLOCK_RESET"

export const TEACHER_CONTENT_STATUS_REQUEST = "TEACHER_CONTENT_STATUS_REQUEST"
export const TEACHER_CONTENT_STATUS_SUCCESS = "TEACHER_CONTENT_STATUS_SUCCESS"
export const TEACHER_CONTENT_STATUS_FAIL = "TEACHER_CONTENT_STATUS_FAIL"
export const TEACHER_CONTENT_STATUS_RESET = "TEACHER_CONTENT_STATUS_RESET"