export const TEACHER_COHORT_REQUEST = "TEACHER_COHORT_REQUEST"
export const TEACHER_COHORT_SUCCESS = "TEACHER_COHORT_SUCCESS"
export const TEACHER_COHORT_FAIL = "TEACHER_COHORT_FAIL"
export const TEACHER_RESET = "TEACHER_RESET"

export const TEACHER_COURSES_REQUEST = "TEACHER_COURSES_REQUEST"
export const TEACHER_COURSES_SUCCESS = "TEACHER_COURSES_SUCCESS"
export const TEACHER_COURSES_FAIL = "TEACHER_COURSES_FAIL"

export const TEACHER_SESSIONS_REQUEST = "TEACHER_SESSIONS_REQUEST"
export const TEACHER_SESSIONS_SUCCESS = "TEACHER_SESSIONS_SUCCESS"
export const TEACHER_SESSIONS_FAIL = "TEACHER_SESSIONS_FAIL"

export const TEACHER_SESSION_SECTIONS_REQUEST = "TEACHER_SESSION_SECTIONS_REQUEST"
export const TEACHER_SESSION_SECTIONS_SUCCESS = "TEACHER_SESSION_SECTIONS_SUCCESS"
export const TEACHER_SESSION_SECTIONS_FAIL = "TEACHER_SESSION_SECTIONS_FAIL"

export const TEACHER_TEMP_SET = "TEACHER_TEMP_SET"
export const TEACHER_TEMP_RESET = "TEACHER_TEMP_RESET"